[toolchain]
anchor_version = "0.29.0"
solana_version = "2.1.4"

[features]
seeds = false
skip-lint = false

[programs.localnet]
test_chlen = "3ksKj17cGKP7oZ8YtexAEbvxqNQaBfSB3F5ZCLjBX79X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
